import Login from './login'
import HqMain from './hqMain'
import Centers from './centers'
import AddCenter from '../components/pages/centers/AddCenter';
import EditCenter from '../components/pages/centers/EditCenter';
import Courses from './courses'
import AddCourse from '../components/pages/courses/AddCourse';
import EditCourse from '../components/pages/courses/EditCourse';
import ViewCourse from '../components/pages/courses/ViewCourse';
import CenterKpi from '../components/pages/centerKpi/CenterKpi';
import Packages from '../components/pages/packages/Packages';
import AddPackage from '../components/pages/packages/AddPackage';
import EditPackage from '../components/pages/packages/EditPackage';
import Discounts from '../components/pages/packages/discounts/Discounts';
import AddDiscount from '../components/pages/packages/discounts/AddDiscount';
import EditDiscount from '../components/pages/packages/discounts/EditDiscount';
import Others from '../components/pages/packages/others/Others';
import AddOthers from '../components/pages/packages/others/AddOthers'
import EditOthers from '../components/pages/packages/others/EditOthers'
import Inventories from '../components/pages/inventories/Inventories';
import AddInventory from '../components/pages/inventories/AddInventory';
import EditInventory from '../components/pages/inventories/EditInventory'
import StudentInvoicing from '../components/pages/invoicing/student/StudentInvoicing';
import StudentInvoice from '../components/pages/invoicing/student/StudentInvoice';
import CenterInvoicing from '../components/pages/invoicing/center/CenterInvoicing';
import CenterInvoice from '../components/pages/invoicing/center/CenterInvoice';
import Students from '../components/pages/students/Students';
import AddStudent from '../components/pages/students/AddStudent';
import EditStudent from '../components/pages/students/EditStudent';
import Attendence from './attendence';
import AttendenceHistory from '../components/pages/attendence/AttendenceHistory';
import PayHq from '../components/pages/payHq/PayHq';
import PaymentHistory from '../components/pages/payHq/PaymentHistory';
import Report from '../components/pages/report/Report';
import Issue2Student from '../components/pages/issue&request/issue2Student/Issue2Student'
import Request2Hq from '../components/pages/issue&request/Request2Hq'
import PayByStudent from '../components/pages/payByStudent/PayByStudent';
import PbsPaymentHistory from '../components/pages/payByStudent/PaymentHistory';
import Contact from '../components/pages/contact/Contact';
import Enquires from '../components/pages/enquires/Enquires'
import Settings from '../components/pages/settings/Settings';
import AddUser from '../components/pages/settings/AddUser';
import EditUser from '../components/pages/settings/EditUser';

export { Login, HqMain, Centers, AddCenter, EditCenter, Courses, AddCourse, EditCourse, ViewCourse, CenterKpi, Packages, AddPackage, EditPackage, Discounts, AddDiscount, EditDiscount, Others, AddOthers, EditOthers, Inventories, AddInventory, EditInventory, StudentInvoicing, StudentInvoice, CenterInvoicing, CenterInvoice, Students, AddStudent, EditStudent, Attendence, AttendenceHistory, PayHq, PaymentHistory, Report, Issue2Student, Request2Hq, PayByStudent, PbsPaymentHistory, Contact, Enquires, Settings, AddUser, EditUser }