export const registerUserUrl = '/user/register'
export const loginUserUrl = '/user/login'
export const getUsersUrl = '/user/all'
export const getUserUrl = '/user/me'
export const enumsUrl = '/enums'
export const createPicUrl = '/pic'
export const createBankUrl = '/bank'
export const centerUrl = '/center'