export const url_login = '/login'
export const url_hq = '/hq'
export const url_centers = '/centers'
export const url_addCenter = '/add-center'
export const url_editCenter = '/edit-center'
export const url_courses = '/courses'
export const url_addCourse = '/add-course'
export const url_editCourse = '/edit-course'
export const url_viewCourse = '/view-course'
export const url_student = '/student'
export const url_registerStudent = '/register-student'
export const url_editStudent = '/edit-student'
export const url_attendence = '/attendence'

