export const url_login = '/login'
export const url_hq = '/hq'
export const url_center = '/center'
export const url_student = '/student'
export const url_registerStudent = '/register-student'
export const url_editStudent = '/edit-student'
export const url_course = '/course'
